# Generated by Django 4.2.5 on 2026-01-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_myapp_timestamp_myapp_author_myapp_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myapp',
            table='myapp_diary',
        ),
    ]
