# Generated by Django 4.2.5 on 2026-01-27 01:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_myapp_timestamp_myapp_author_myapp_created_at'),
    ]

    # 本番DBには myapp_myapp が存在せず、既に myapp_diary があるため
    # テーブルrename(ALTER TABLE) を実行すると落ちる。
    # モデル側(db_table)で参照先を切り替えるだけにして、DB操作は行わない。
    operations = []
