# Generated by Django 4.2.5 on 2026-01-27 04:21
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_myapp_table"),
    ]

    # 本番DBを壊さないため、DB操作はしない（状態だけ進める）
    operations = []
