# Generated by Django 4.2.5 on 2026-01-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_myapp_options_alter_mymail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mymail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
    ]
