# Generated by Django 4.2.5 on 2026-01-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_myapp_options_alter_mymail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myapp',
            table='myapp_diary',
        ),
        migrations.AlterModelTable(
            name='mymail',
            table='myapp_mymail',
        ),
    ]
