# Generated by Django 4.2.5 on 2026-02-04 00:43
from django.db import migrations

def add_age_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor  # 'sqlite' / 'postgresql' / 'mysql' etc.

    if vendor == "sqlite":
        # SQLite は IF NOT EXISTS が使えない（かつ ADD COLUMN は一度しか通らない）
        # 既に age があるなら何もしない、なければ追加する
        columns = [c.name for c in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), "person"
        )]
        if "age" not in columns:
            schema_editor.execute("ALTER TABLE person ADD COLUMN age integer;")

    elif vendor == "postgresql":
        schema_editor.execute("ALTER TABLE person ADD COLUMN IF NOT EXISTS age integer;")

    else:
        # 他DBはひとまず素直に（必要ならここをDB別に調整）
        schema_editor.execute("ALTER TABLE person ADD COLUMN age integer;")

def drop_age_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    if vendor == "postgresql":
        schema_editor.execute("ALTER TABLE person DROP COLUMN IF EXISTS age;")
    elif vendor == "sqlite":
        # SQLite は DROP COLUMN が古い環境だと使えないことが多いので無理に消さない
        pass
    else:
        schema_editor.execute("ALTER TABLE person DROP COLUMN age;")

class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_myapp_table_alter_mymail_table"),
    ]

    operations = [
        migrations.RunPython(add_age_column, reverse_code=drop_age_column),
    ]
