# Generated by Django 4.2.5 on 2026-06-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_fix_add_message_column'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myapp',
            table='myapp_myapp',
        ),
    ]
