# Generated by Django 4.2.5 on 2026-01-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開'),
        ),
    ]
